### ISSUE TITLE
Not able to run in windows

### ISSUE THREAD

**Issue by delaneyj** [jscad/jscad-desktop#14]
```
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:605:28)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```

What is it trying to do here? Sure there is a node way to do this cross platform.  Happy to help, just want a use case to work against.

**Comment by kaosat-dev** [comment]
Hi @delaneyj !
Good catch ! It should just be trying to run the local app via the electron tool in node_modules.
Actually somebody in the community forums just found a solution for this, so I am including it in the PR that I will merge in a few minutes :)
once you have updated you can use the `npm run dev-win` command to launch under Windows!
Do not hesitate to reopen the issue if that fails
